version: "3.9"

services:

  mongodb:
    image: mongo:latest
    container_name: ${PROJECT_NAME}_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - application

volumes:
  mongodb_data:

networks:
  application:
    driver: host
