services:

  mongodb:
    image: mongo:latest
    container_name: quizbase_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./dump:/data/db/dump
    networks:
      - local-dev

volumes:
  mongodb_data:

networks:
  local-dev:
    driver: bridge