version: '3.8'

services:
  reverse-proxy:
    image: nginx:1.25.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-conf:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - application
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - application

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - application
      - internal
    depends_on:
      - mongodb

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-conf:/etc/letsencrypt

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./dump:/data/db/dump
    networks:
      - internal

  matomo-db:
    image: mariadb:latest
    container_name: matomo-db
    volumes:
      - matomo-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: matomo
      MYSQL_USER: matomo
      MYSQL_PASSWORD: matomo

  matomo:
    image: matomo:latest
    container_name: matomo
    ports:
      - "8080:80"
    links:
      - matomo-db
    environment:
      MATOMO_DATABASE_HOST: matomo-db
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
      MATOMO_DATABASE_USERNAME: matomo
      MATOMO_DATABASE_PASSWORD: matomo
      MATOMO_DATABASE_DBNAME: matomo
    volumes:
      - matomo-data:/var/www/html

volumes:
  certbot-conf:
  certbot-www:
  mongodb_data:
  matomo-db-data:
  matomo-data:

networks:
  application:
    driver: bridge
  internal:
    driver: bridge
    internal: true