version: '3.8'

services:
  frontend:
    image: nginx:1.25.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-conf:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - backend
    networks:
      - application

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    #    ports:
    #      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=production
    networks:
      - application

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
#    command: certonly --webroot --webroot-path=/var/www/certbot --email peter.majmesku@gmail.com --agree-tos --no-eff-email -d mobilefish.de

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./dump:/data/db/dump
    networks:
      - application

volumes:
  node_modules:
  certbot-conf:
  certbot-www:

networks:
  application:
    driver: bridge
