version: '3.8'

services:
  reverse-proxy:
    image: nginx:1.25.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-conf:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - application
    restart: unless-stopped

  frontend:
    build:
      context: ./client-next
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - application

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - application

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-conf:/etc/letsencrypt

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./dump:/data/db/dump
    networks:
      - application

volumes:
  certbot-conf:
  certbot-www:
  mongodb_data:

networks:
  application:
    driver: bridge
