version: "3.9"

services:

  php:
    build:
      context: ./../
      dockerfile: container/Dockerfile
      target: development
    container_name: ${PROJECT_NAME}_php
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1024M"
        reservations:
          cpus: "1.0"
          memory: "1024M"
    read_only: true
    tmpfs:
      - /tmp:uid=1000,gid=1000
      - /.composer:uid=1000,gid=1000
      - /var/log:uid=1000,gid=1000
      - /var/log/nginx:uid=1000,gid=1000
      - /var/run:uid=1000,gid=1000
    user: 1000:1000
    volumes:
      - ./../symfony:/var/www/application
      - ./../symfony/var:/var/www/application/var:uid=1000,gid=1000
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "gewerbe.ddev.site:host-gateway"
    networks:
      application:
        aliases:
          - questions_db.local

  mongodb:
    image: mongo:latest
    container_name: ${PROJECT_NAME}_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - application

volumes:
  mongodb_data:

networks:
  application:
    driver: bridge
