describe('template spec', () => {
  it('Login required', () => {
    cy.visit('http://172.17.30.97:9000/')
    cy.contains('Login')
        .parent()
        .find('button')
    cy.get('input')
        .type('sandra');
    cy.get('button').click()
    cy.contains('button', 'Quiz erstellen')
        .click()
  })
  it('Check necessary buttons', () => {
    cy.visit('http://172.17.30.97:9000/')
    cy.contains('Login')
        .parent()
        .find('button')
    cy.get('input')
        .type('sandra');
    cy.get('button').click()
    cy.contains('button', 'Quiz erstellen')
    cy.contains('button', 'Quiz beitreten')
    cy.contains('button', 'Kategorie erstellen')
  })
  it('Play singleplayer game', () => {
    cy.visit('http://172.17.30.97:9000/')
    cy.contains('Login')
        .parent()
        .find('button')
    cy.get('input')
        .type('sandra');
    cy.get('button').click()
    cy.contains('button', 'Quiz erstellen').click()
    cy.get('input')
        .type('Peter');
    cy.get('button').click()
    cy.contains('button', 'Auf WhatsApp teilen').should('exist')
    cy.contains('button', 'Link kopieren').should('exist')
    cy.contains('button', 'Bereit').click()
    // Select the first game category
    cy.get('button').first().click()
    cy.contains('button', 'Leicht').click()
    // Check the necessary items on one question view
    cy.contains('h3', '(leicht)').should('exist')
    cy.contains('h2', 'Frage 1/10:').should('exist')
    cy.contains('h3', 'Punktestand').should('not.exist')
    cy.contains('button', 'Nächste Frage').should('be.disabled')
    // Answer the question
    cy.get('button').first().click()
    cy.contains('#explanation', 'Korrekte Antwort: ').should('exist')
    cy.contains('h3', 'Punktestand').should('exist')
    cy.contains('button', 'Nächste Frage').should('not.be.disabled')
    cy.contains('button', 'Nächste Frage').click()
    // Answer all the questions
    cy.get('button').first().click()
    cy.contains('button', 'Nächste Frage').click()
    cy.get('button').first().click()
    cy.contains('button', 'Nächste Frage').click()
    cy.get('button').first().click()
    cy.contains('button', 'Nächste Frage').click()
    cy.get('button').first().click()
    cy.contains('button', 'Nächste Frage').click()
    cy.get('button').first().click()
    cy.contains('button', 'Nächste Frage').click()
    cy.get('button').first().click()
    cy.contains('button', 'Nächste Frage').click()
    cy.get('button').first().click()
    cy.contains('button', 'Nächste Frage').click()
    cy.get('button').first().click()
    cy.contains('button', 'Nächste Frage').click()
    cy.get('button').first().click()
    cy.contains('button', 'Nächste Frage').click()
    cy.contains('h3', 'Fragen und Antworten').should('exist')
  })
})